### ISSUE TITLE
Error when using nvd3 in angular 2.0 with typescript

### ISSUE THREAD

**Issue by robbatt** [novus/nvd3#1503]
Hi there,

I was trying to get nvd3 to work with angular 2.0 beta and typescript. The problem does not seem to be on angular but on nvd3 side, but I am not a JS pro. Please take a look at the following plunkr link reproducing the problem. Hope this helps somebody.

plunker producing the error: https://plnkr.co/edit/USEzqyDhADpeiE7HOIgW?p=preview

`TypeError: Cannot read property 'disabled' of undefined
    at https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.js:6111:57
    at Array.map (native)
    at https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.js:6111:30
    at _set (https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.js:1261:24)
    at update (https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.js:1282:18)
    at HTMLElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.js:6149:18)
    at https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.14/d3.js:8868:16
    at d3_selection_each (https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.14/d3.js:967:30)
    at Array.d3_transitionPrototype.each (https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.14/d3.js:8866:9)
    at Array.chart (https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.js:6131:19)
`

Keep up the great work,
Rob

**Comment by liquidpele** [comment]
Unless you can reproduce the issue with just nvd3, I'm not sure how you can say it's an nvd3 issue... especially trying to use it with typescript and angular (both of which have plenty of gotchas).  

If you do find the issue and there is something nvd3 can do to make it easier to work with angular 2, then please send us a pull request.   However I can't test with every framework/etc so we rely on community contributions for most things.   Also, you might want to hit up the angular-nvd3 project guys, not sure if they're looking at angular2 or not.
