### ISSUE TITLE
Meteor Tinytests- error during executing test 

### ISSUE THREAD

**Issue by demon1233** [novus/nvd3#1877]
I take a  error during executing  spacejam test-packages ./
then i take 
spacejam: spawning meteor
spacejam: killing meteor
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by liquidpele** [comment]
The meteor stuff was submitted as pull requests from community members, not really familiar with any of it myself... hopefully someone who is can chime in :)
