### ISSUE TITLE
NVD3 not compatible with Node JS 

### ISSUE THREAD

**Issue by sklencar** [novus/nvd3#1971]
Hi,

I would like to report a dependency bug since NVD3 lib us using window and selecting `this` which causes a problem. I am trying to use NVD3 for generating graphs on Node JS server (using it also on client side and don't want to write code twice). Node JS has no window object which thrown a reference error:

`ReferenceError: window is not defined`
`at Object.nv.interactiveGuideline (/home/../graph-js-service/node_modules/nvd3/build/nv.d3.js:201:23)`
`at Object.nv.models.lineChart (/home/../graph-js-service/node_modules/nvd3/build/nv.d3.js:6735:33)`

After defining mocked window object as 

`var jsdom = require("jsdom");`
`var document = jsdom.jsdom();`
`global.window = {document: document};);` 

I can't define a container and dimension for a graph. Thus, the library probably cant find any container and takes default dimension instead. Looking at the code, the d3 select of `this` is commonly used which could be also an issue. I am using d3 (3.5.17), nvd3( 1.8.5) and generated nvd3 facade for Scala.

I would be glad for any fix and also for an option to pass a dom object or d3 selection as a container for any type of graph (including axis, lines,etc.). In my view, it would be more convenient for the general usage, especially for Node JS.

Thanks.

Best,
Viktor Sklencar

**Comment by bgth** [comment]
Please check similar issue [#1952](https://github.com/novus/nvd3/issues/1952). Also please check d3js server side example [link](https://github.com/gregjopa/d3-server-side-demo)

**Comment by KidA78** [comment]
@bgth, @sklencar: why would nvd3 (or d3js for that matter) even need to live on the server-side?   @sklencar what is it that you're trying to do?

**Comment by sklencar** [comment]
@KidA78 Simply, I am showing graphs in the browser, but want to export them as well by using Jasper reports (DynamicReports). By using the same code and css, they suppose to look the same which is the key (in addition, there is no need to write code twice). I don't like the idea of client sending the whole SVG file in the request, so I decided to go with Node JS server and js generated from my Scala graph builder.

It works quite well, but I had to use a workaround of mocked window object and be fine with default dimension of a container for a graph. This holds only for nvd3 since it uses (in my view) hard coded `d3.select(this)` a lot instead of giving an option to pass own selection or DOM object. When I am using d3 for drawing additional axis, it works well also on Node JS server.

**Comment by bgth** [comment]
@sklencar For svg to pdf on the browser side, we have used [svg_to_pdf](https://github.com/haochi/svg_to_pdf) successfully. You can try and see if it fits.
Also, if you were successful in creating nvd3 charts on server side, can you please share an example of how you did it?

**Comment by sklencar** [comment]
@bgth  Here is a rough example how I create a graph using nvd3 and node js. Sorry for quite late answer.

A request is created on client side, sent and handle by the server:

```
def exportOverview(id: Long): Action[AnyContent] = tenantActionBuilder.requireReadAccess(User) { implicit request =>
    val data = PageService.withTC.getGraphData(id)
    request.withJpaTransaction { implicit em =>
      val wsRequest: WSRequest = ws.url(URL_GRAPH_NODE_SERVER + ":" + PORT_GRAPH_NODE_SERVER).withQueryString("data" -> write[Seq[GraphData]](data))

      wsRequest.get().map { response =>
        generateReport(response.body)
      }
    }
  }

  def generateReport(rawSvg: String)(implicit tc: TenantContext): Result = {
    val graphSvg: Renderable = BatikRenderer.getInstance(new ByteArrayInputStream(rawSvg.getBytes()))
    val pdfFile = File.createTempFile("temp", ".pdf")
    val pdfExporter: JasperPdfExporterBuilder = DynamicReports.export.pdfExporter(pdfFile)

    val result = report()
      .setTemplate(ReportTemplate.template)
      .setPageFormat(PageType.A4, PageOrientation.PORTRAIT)
      .title(ReportTemplate.header)
      .pageFooter(ReportTemplate.footer)
      .toPdf(pdfExporter)

    val jp: JasperPrint = report.toPdf(new FileOutputStream(pdfFile)).toJasperPrint
    Ok(JasperExportManager.exportReportToPdf(result.toJasperPrint)).as("application/pdf")
  }
```

The node JS side:

```
var http =  require('http');
var fs = require('fs');
var d3 = require('d3');
var nvd3 = require('nvd3');
var jsdom = require("jsdom");
var url = require('url');
var serializer = require('xmlserializer');

// A file of generated javascript from my scala code
var path = './../modules/react-app/client/target/scala-2.11/reactappclient-fastopt.js'; 
var builderModule = require(path);

// accoridng NVD3 default vals in nvd3/utils#nv.utils.availableHeight and nv.utils.availableWidth
var printWidth = 960;
var printHeight = 400;

global.NVD3 = nvd3;
global.d3 = d3;

/ Configure our HTTP server to respond.
var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/html; charset=utf-8"});
  var query = url.parse(request.url, true).query;
  var data = query['data'];

  var document = jsdom.jsdom();
  global.window = {document: document};
  var container = d3.select(document.body).node();

  var startTime = new Date().getTime();
  var builder = global/path/to/GraphBuilder();
  // creates svg in container
  builder.renderToString(data, d3.select(container).node(), printWidth, printHeight);

  var svgNode = d3.select(container).select('svg').node();
  svgNode.setAttribute('xlink', 'http://www.w3.org/1999/xlink');
  svgNode.setAttribute("xmlns", "http://www.w3.org/2000/svg");

  var svgString = serializer.serializeToString(svgNode);
  svgString = svgString.replace(/(\w+)?:?xlink=/g, 'xmlns:xlink='); // Fix root xlink without namespace
  svgString = svgString.replace(/NS\d+:href/g, 'xlink:href'); // Safari NS namespace fix
  var endTime = new Date().getTime();
  response.end(svgString);
});

// Listen on port 8000, IP defaults to 127.0.0.1
server.listen(8000);

console.log("Graph JS Server running at http://127.0.0.1:8000/");
```
Scala Graph builder on server side (used also on client side). This method is called from node JS server:
```
  @JSExport
  def renderToString(dataJson: String, containerNode: dom.EventTarget, printWidth: Double, printHeight: Double) = {

    val graphData: Seq[GraphData] = read[Seq[GraphData]](dataJson)
    val isForExport = targetNode != null
    val documentSelection: dom.EventTarget = if (isForExport) targetNode else d3.select("#" + containerName).node()

    val series = getGraphData(graphData) // returns regular series Array
    val chart = NVD3.models.multiChart()

    val boundingRect: Dynamic = d3.select(documentSelection).dynamic.node().getBoundingClientRect()
    val width = if (boundingRect.width.asInstanceOf[Double] == 0) printWidth else boundingRect.width.asInstanceOf[Double]
    val height = if (boundingRect.height.asInstanceOf[Double] == 0) printHeight else boundingRect.height.asInstanceOf[Double]

    d3.select(documentSelection).append("svg")
        .attr("class", GRAPH_CLASS)
        .attr("width", width + "px").attr("height", height + "px")

    d3.select(documentSelection).select("." + GRAPH_CLASS)
        .datum(series)
        .dynamic
        .call(chart)
  }
```
I hope it helps someone.

**Comment by sklencar** [comment]
As I wrote before, nvd3 cant calculate available height and width with functions in nv.utils on Node JS server. Therefore they always return hardcoded default values.

```
/*
Sanitize and provide default for the container height.
*/
nv.utils.sanitizeHeight = function(height, container) {
    return (height || parseInt(container.style('height'), 10) || 400);
};
/*
Sanitize and provide default for the container width.
*/
nv.utils.sanitizeWidth = function(width, container) {
    return (width || parseInt(container.style('width'), 10) || 960);
};
```

However, our own default value can be returned if they are overwritten like this in node js server:
```
  nvd3.utils.sanitizeHeight = function(height, container) {
    return (height || parseInt(container.style('height'), 10) || CUSTOM_HEIGHT);
  };

  nvd3.utils.sanitizeWidth = function(width, container) {
    return (width || parseInt(container.style('width'), 10) || CUSTOM_WIDTH);
  };
```
It is not best practice at all, but the idea can help someone. 
Note, that variable nvd3 is defined like "var nvd3 = require('nvd3');" (For better context, see comment above).

**Comment by jeznag** [comment]
Have you tried using benv? NVD3 works fine for me on node with benv enabled.

https://github.com/COzero/nvd3/blob/feature/line-with-focus-plus-secondary/test/mocha/lineWithFocusPlusSecondaryChart.js#L29
