### ISSUE TITLE
Getting Exception Object doesn't support property or method 'watchTransition'

### ISSUE THREAD

**Issue by TojThank** [novus/nvd3#2026]
Hello,
 I am getting exception Object doesn't support property or method 'watchTransition' 
this is happening with Multibarchart 
Please find the code block 

var chart = nv.models.multiBarChart()
var d3elem = d3.select(["#", this.element[0].id].join(""));
d3elem.append('svg');
var data  = [{
	values: [{ x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 1 }, { x: 4, y: 1 }, { x: 5, y: 1 }, { x: 6, y: 3 }, { x: 7, y: 2 }],    key: " Data A",    color: "#32BED7"	},
    {    values: [{ x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 10 }, { x: 3, y: 10 }, { x: 4, y: 10 }, { x: 5, y: 10 }, { x: 6, y: 10 }, { x: 7, y: 10 }],     key: "Non Data",    color: "#EDC774"    }    ];

  d3.select(["#", this.element[0].id, ' svg'].join("")).datum(data).call(chart);

Library Info 
D3 version 4.8.0
 nvd3 version 1.8.5-dev

Please advise

**Comment by TojThank** [comment]
Please find stack trace from chrome browser 
"TypeError: R.watchTransition is not a function
    at SVGGElement.<anonymous> (http://localhost/Sol/bundles/FMLibScript?v=4gmwbN8xGxWILnwyIF3ALQgrcD4AVUfrnZBQ_0CblaA1:139:1949)
    at http://localhost/sol/Scripts/App/d3.v3.min.js:3:7614
    at N (http://localhost/sol/Scripts/App/d3.v3.min.js:1:3365)
    at Array.Ro.each (http://localhost/sol/Scripts/App/d3.v3.min.js:3:7589)
    at Array.b (http://localhost/sol/bundles/FMLibScript?v=4gmwbN8xGxWILnwyIF3ALQgrcD4AVUfrnZBQ_0CblaA1:138:29610)
    at Array.Ro.call (http://localhost/sol/Scripts/App/d3.v3.min.js:3:7689)
    at SVGSVGElement.<anonymous> (http://localhost/sol/bundles/FMLibScript?v=4gmwbN8xGxWILnwyIF3ALQgrcD4AVUfrnZBQ_0CblaA1:139:7279)
    at http://localhost/sol/Scripts/App/d3.v3.min.js:3:7614
    at N (http://localhost/sol/Scripts/App/d3.v3.min.js:1:3365)
    at Array.Ro.each (http://localhost/sol/Scripts/App/d3.v3.min.js:3:7589)"

**Comment by TojThank** [comment]
Got the issue, d3.v3.min.js was referenced after nvd3 . Removed it and it is working fine.
